### ISSUE TITLE
提示连接失败

### ISSUE THREAD

**Issue by l2js** [c0bra/deviceframe#17]
Downloading frame Apple Macbook Pro 15" [             ] 32/bps 1% 3.1s{ RequestError: connect ECONNREFUSED 31.13.86.8:443
    at ClientRequest.req.once.err (*/Developer/NodeJS/lib/node_modules/deviceframe/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  code: 'ECONNREFUSED',
  host: 'cdn.rawgit.com',
  hostname: 'cdn.rawgit.com',
  method: 'GET',
  path: '/c0bra/deviceframe-frames/2.0.1/Computers/Apple%20Macbook%20Pro/15%22/Device/Apple%20Macbook%20Pro%2015%22.png',
  protocol: 'https:',
  url: 'https://cdn.rawgit.com/c0bra/deviceframe-frames/2.0.1/Computers/Apple%20Macbook%20Pro/15%22/Device/Apple%20Macbook%20Pro%2015%22.png' }
(node:4629) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by c0bra** [comment]
@shiditime are you able to manually pull down the image? https://cdn.rawgit.com/c0bra/deviceframe-frames/2.0.1/Computers/Apple%20Macbook%20Pro/15%22/Device/Apple%20Macbook%20Pro%2015%22.png

**Comment by c0bra** [comment]
No response; closing
